export const CV_LIST_REQUEST = 'CV_LIST_REQUEST'
export const CV_LIST_SUCCESS = 'CV_LIST_SUCCESS'
export const CV_LIST_FAIL = 'CV_LIST_FAIL'


export const CV_DETAILS_REQUEST = 'CV_DETAILS_REQUEST'
export const CV_DETAILS_SUCCESS = 'CV_DETAILS_SUCCESS'
export const CV_DETAILS_FAIL = 'CV_DETAILS_FAIL'


export const CV_DELETE_REQUEST = 'CV_DELETE_REQUEST'
export const CV_DELETE_SUCCESS = 'CV_DELETE_SUCCESS'
export const CV_DELETE_FAIL = 'CV_DELETE_FAIL'

export const CV_CREATE_REQUEST = 'CV_CREATE_REQUEST'
export const CV_CREATE_SUCCESS = 'CV_CREATE_SUCCESS'
export const CV_CREATE_FAIL = 'CV_CREATE_FAIL'
export const CV_CREATE_RESET = 'CV_CREATE_RESET'


export const CV_UPDATE_REQUEST = 'CV_UPDATE_REQUEST'
export const CV_UPDATE_SUCCESS = 'CV_UPDATE_SUCCESS'
export const CV_UPDATE_FAIL = 'CV_UPDATE_FAIL'
export const CV_UPDATE_RESET = 'CV_UPDATE_RESET'

export const CV_TOP_REQUEST = 'CV_TOP_REQUEST'
export const CV_TOP_SUCCESS = 'CV_TOP_SUCCESS'
export const CV_TOP_FAIL = 'CV_TOP_FAIL'



export const CV_LIST_MY_REQUEST = 'CV_LIST_MY_REQUEST'
export const CV_LIST_MY_SUCCESS = 'CV_LIST_MY_SUCCESS'
export const CV_LIST_MY_FAIL = 'CV_LIST_MY_FAIL'
export const CV_LIST_MY_RESET = 'CV_LIST_MY_RESET'