export const TEACHER_LIST_REQUEST = 'TEACHER_LIST_REQUEST'
export const TEACHER_LIST_SUCCESS = 'TEACHER_LIST_SUCCESS'
export const TEACHER_LIST_FAIL = 'TEACHER_LIST_FAIL'


export const TEACHER_DETAILS_REQUEST = 'TEACHER_DETAILS_REQUEST'
export const TEACHER_DETAILS_SUCCESS = 'TEACHER_DETAILS_SUCCESS'
export const TEACHER_DETAILS_FAIL = 'TEACHER_DETAILS_FAIL'


export const TEACHER_DELETE_REQUEST = 'TEACHER_DELETE_REQUEST'
export const TEACHER_DELETE_SUCCESS = 'TEACHER_DELETE_SUCCESS'
export const TEACHER_DELETE_FAIL = 'TEACHER_DELETE_FAIL'

export const TEACHER_CREATE_REQUEST = 'TEACHER_CREATE_REQUEST'
export const TEACHER_CREATE_SUCCESS = 'TEACHER_CREATE_SUCCESS'
export const TEACHER_CREATE_FAIL = 'TEACHER_CREATE_FAIL'
export const TEACHER_CREATE_RESET = 'TEACHER_CREATE_RESET'


export const TEACHER_UPDATE_REQUEST = 'TEACHER_UPDATE_REQUEST'
export const TEACHER_UPDATE_SUCCESS = 'TEACHER_UPDATE_SUCCESS'
export const TEACHER_UPDATE_FAIL = 'TEACHER_UPDATE_FAIL'
export const TEACHER_UPDATE_RESET = 'TEACHER_UPDATE_RESET'


export const TEACHER_CREATE_REVIEW_REQUEST = 'TEACHER_CREATE_REVIEW_REQUEST'
export const TEACHER_CREATE_REVIEW_SUCCESS = 'TEACHER_CREATE_REVIEW_SUCCESS'
export const TEACHER_CREATE_REVIEW_FAIL = 'TEACHER_CREATE_REVIEW_FAIL'
export const TEACHER_CREATE_REVIEW_RESET = 'TEACHER_CREATE_REVIEW_RESET'

export const TEACHER_TOP_REQUEST = 'TEACHER_TOP_REQUEST'
export const TEACHER_TOP_SUCCESS = 'TEACHER_TOP_SUCCESS'
export const TEACHER_TOP_FAIL = 'TEACHER_TOP_FAIL'


